config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/index'

  resource :user
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
    member do
      post :upvote
      post :downvote
    end
  end

  resources :comments, only: [:create, :show]
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :text
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ActiveRecord::Base
  validates :title, :moderator_id, presence: true

  belongs_to :moderator,
    class_name: "User",
    foreign_key: :moderator_id,
    primary_key: :id

  # has_many :posts,
  #   class_name: "Post",
  #   foreign_key: :sub_id,
  #   primary_key: :id

  has_many :post_subs
  has_many :posts, through: :post_subs

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_correct_moderator, only: [:edit, :update]

  def index
    @subs = Sub.all
    render :index
  end

  def show
    @sub = Sub.includes(:posts => :author).find(params[:id])
    render :show
  end

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      flash[:success] = ["Sub successfully created"]
      redirect_to sub_url(@sub)
    else
      flash[:error] = @sub.errors.full_messages
      render :new
    end
  end

  def destroy
    sub = Sub.find(params[:id])
    sub.destroy
    redirect_to subs_url
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      flash[:success] = ["Sub successfully updated"]
      redirect_to sub_url(@sub)
    else
      flash[:error] = @sub.errors.full_messages
      render :edit
    end
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  private
  def require_correct_moderator
    sub = Sub.find(params[:id])
    redirect_to subs_url if current_user.id != sub.moderator_id
  end

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/views/subs/_form.html.erb
<% action = sub.new_record? ? subs_path : sub_path(sub) %>
<% button =  sub.new_record? ? "Create Sub" : "Edit Sub" %>

<form action="<%= action%>" method="post">
  <%= auth_token %>
  <% unless sub.new_record? %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <label for="sub_title">Title: </label>
  <input type="text" name="sub[title]" value="<%= sub.title %>">
  <br><br>

  <label for="sub_description">Description: </label>
  <textarea name="sub[description]" rows="8" cols="40"><%= sub.description %></textarea>

  <input type="submit"  value="<%= button %>">
</form>

app/views/subs/_post.html.erb
<p>
  ( <%= post.count_votes[:score] %> )
  <%= link_to post.title, post_url(post) %>
</p>
<p><em>
  submitted by
  <%= post.author.user_name %> 
  <%= time_ago_in_words(post.created_at) %> 
  ago</em>
</p>

app/views/subs/_post_form.html.erb
<h3>Create new post</h3>
<%= render 'posts/form' %>

app/views/subs/_sub.html.erb
<li>
  <%= link_to sub.title, sub_url(sub) %>
  <% if is_moderator?(current_user, sub) %> | 
    <%= link_to "Edit", edit_sub_url(sub) %> | 
    <%= link_to 'Delete', sub_url(sub), method: :delete %>
  <% end %>
</li>

app/views/subs/edit.html.erb
<h1>Edit Sub</h1>
<%= render 'form', sub: @sub %>
<%= link_to "Back to Subs", subs_url %>

app/views/subs/index.html.erb
<h1>All Subs</h1>
<ul>
<%= render @subs %>
</ul>

<%= link_to "Create new Sub", new_sub_url %>

app/views/subs/new.html.erb
<h1>Create New Sub</h1>
<%= render 'form', sub: @sub %>
<%= link_to "Back to Subs", subs_url %>

app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>
<h4>
  <em><%= @sub.description %></em>
</h4>

<h3>Posts</h3>
<%= render partial: 'post', collection: @sub.posts %>
<hr>
<%= link_to "Make a new Post", new_post_url %>
<br>
<%= link_to "Back to subs", subs_url %>