config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/index'

  resource :user
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
    member do
      post :upvote
      post :downvote
    end
  end

  resources :comments, only: [:create, :show]
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  validates :title, :author_id, presence: true
  validate  :has_a_sub

  belongs_to :author,
    class_name: "User",
    foreign_key: :author_id,
    primary_key: :id

  has_many :comments
  has_many :post_subs, inverse_of: :post, dependent: :destroy
  has_many :subs, through: :post_subs
  has_many :votes, as: :votable, dependent: :destroy

  def comments_by_parent_id
    result = Hash.new { |h, k| h[k] = [] }
    comments.each do |comment|
      result[comment.parent_comment_id] << comment
    end
    result
  end

  def count_votes
    result = Hash.new(0)
    votes = Vote.where(votable_type: "Post", votable_id: id)
    result[:total] = votes.count

    votes.each do |vote|
      result[:score] += vote.value
    end

    result
  end

  private
  def has_a_sub
    if self.subs.empty?
      errors[:errors] = "must belong to a sub"
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :require_correct_author, only: [:edit, :update, :destroy]

  def show
    @post = Post.includes(:author,:comments).find(params[:id])
    @comments_by_parent_id = @post.comments_by_parent_id
    render :show
  end

  def new
    @post = Post.new(author_id: current_user.id)
    @subs = Sub.all
    render :new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id

    if @post.save
      flash[:success] = ["Made Post"]
      redirect_to post_url(@post)
    else
      @subs = Sub.all
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @subs = Sub.all
    @post = Post.find(params[:id])
    render :edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = ["Updated Post"]
      redirect_to post_url(@post)
    else
      @subs = Sub.all
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to sub_url(@post.sub_id)
    else
      redirect_to post_url(@post.id), status: 404
    end
  end

  def upvote
    vote(1)
  end

  def downvote
    vote(-1)
  end


  private
  def vote(up_or_down)
    post = Post.find(params[:id])
    voted = Vote.find_by(user_id: current_user.id,
                          votable_id: post.id,
                          votable_type: "Post")

    vote = Vote.new(value: up_or_down,
                    user_id: current_user.id,
                    votable_type: "Post",
                    votable_id: post.id)
    if voted
      voted.destroy
      vote.save if voted.value != up_or_down
    else
      vote.save
    end
    redirect_to post_url(post)
  end

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end

  def require_correct_author
    @post = Post.find(params[:id])
    redirect_to sub_url(@post.sub_id) unless current_user.id == @post.author_id
  end
end

app/views/posts/_comment.html.erb
<div>
  <p>
    Comment by <%= comment.author.user_name %> made
    <%= time_ago_in_words(comment.updated_at) %> ago
  </p>
  <p>
    <%= comment.content %>
  </p>
  <p><%= link_to "See Comment", comment_url(comment) %></p>
  <ul>
    <% comment_by_parent_id[comment.id].each do |comment| %>
      <%= render partial: "comment", 
                 locals: { comment: comment,
                           comment_by_parent_id: comment_by_parent_id } %>
    <% end %>
  </ul>
</div>

app/views/posts/_comment_form.html.erb
<h4>Add Comment</h4>
<form class="" action="<%= comments_path %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="comment[post_id]" value="<%= post.id %>">

  <textarea name="comment[content]" rows="8" cols="40"></textarea>

  <br><br>
  <input type="submit"  value="Submit">
</form>

app/views/posts/_form.html.erb
<% action = post.new_record? ? posts_path : post_path(post) %>
<% button =  post.new_record? ? "Create Post" : "Edit Post" %>


<form action="<%= action%>" method="post">
  <%= auth_token %>
  <input type="hidden" name="post[sub_ids][]" value="">
  <% unless post.new_record? %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>


  <label for="post_title">Title: </label><br>
  <input type="text" name="post[title]" value="<%= post.title %>">
  <br><br>

  <label for="post_url">URL: </label><br>
  <input type="text" name="post[url]" value="<%= post.url %>">
  <br><br>

  <% subs.each do |sub| %>
    <%= sub.title %>
    <input type="checkbox"
    name="post[sub_ids][]"
    value="<%= sub.id%>"
    <%= "checked" if post.sub_ids.include?(sub.id)  %>>
  <% end %>
  <br><br>

  <label for="post_content">Content: </label><br>
  <textarea name="post[content]" rows="8" cols="40"><%= post.content %></textarea><br>

  <input type="submit"  value="<%= button %>">
</form>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'form', post: @post, subs: @subs %>
<%= button_to "Delete Post", post_url(@post.id), method: :delete %>
<br>
<%= link_to 'Back to Subs', subs_url %>

app/views/posts/new.html.erb
<h1>Create new Post</h1>
<%= render 'form', post: @post, subs: @subs %>

app/views/posts/show.html.erb
<h1>
  <% if @post.url.empty? %>
    <%= @post.title %>
  <% else %>
    <%= link_to @post.title, @post.url %>
  <% end %>
</h1>
<h4>
  by <%= @post.author.user_name %> <%= made_or_edited(@post) %>
  <%= time_ago_in_words(@post.updated_at) %> ago
</h4>
<p>
  Score: <%= @post.count_votes[:score] %> |
  <%= link_to "upvote", upvote_post_url(@post), method: :post %> |
  <%= link_to "downvote", downvote_post_url(@post), method: :post %>
</p>
<p class="well">
  <%= @post.content %>
</p>

<hr>

<h4>Comments ( <%= @post.comments.count %> )</h4>
<% @comments_by_parent_id[nil].each do |comment| %>
  <%= render partial: "comment", 
             locals: { comment: comment, 
                       comment_by_parent_id: @comments_by_parent_id } %>
<% end %>

<%= render partial: "comment_form", locals: { post: @post } %>

<%  if current_user.id == @post.author_id %>
  <%= link_to "Edit Post", edit_post_path(@post.id) %>
<% end %>
<br>
<%= link_to "Back to subs", subs_url %>